### ISSUE TITLE
Corrective changes for several packages during each run with `chocolatey` 2.0.0

### ISSUE THREAD

**Issue by olifre** [puppetlabs/puppetlabs-chocolatey#329]
## Describe the Bug
Corrective changes for several packages during each run after updating to `chocolatey` version 2.0.0. 

## Expected Behavior
No corrective changes during each run after installing a package. 

## Steps to Reproduce
1. Ensure a package resource in the catalog for a package with semantic versioning, e.g. `putty` or `pdfxchangeditor`. 
2. Run Puppet twice. 

## Environment
 - Version: Puppet 6
 - Platform: Windows 10 / 11

## Additional Context
Example changes:
```
/Stage[main]/Profile::Chocolatey/Package[putty]/ensure | ensure changed '0.78.0' to '0.78' (corrective)
/Stage[main]/Profile::Pdfxchange/Package[pdfxchangeeditor]/ensure | ensure changed '9.5.368' to '9.5.368.0' (corrective)
/Stage[main]/Profile::Bginfo/Package[bginfo]/ensure | ensure changed '4.32.0' to '4.32' (corrective)
```
i.e. the changed treatment of versioning is not yet taken care of in this module. 

see also #321

**Comment by trenta** [comment]
I'm seeing this with Puppet 7 (latest).

**Comment by xchotard-talentsoft** [comment]
Same issue here. Seems related to: https://docs.chocolatey.org/en-us/guides/upgrading-to-chocolatey-v2-v6#package-version-normalization
> Version numbers that have fewer than three parts will have the version filled out to three segments (for example, 1.2 will be normalized to 1.2.0).

When `examplepackage 1.0` is installed, Chocolatey will now report `1.0.0`. This is most likely confusing for Puppet. This also occurs at least with `ensure => installed`.

**Comment by Hvid** [comment]
This occurs for me with `ensure => latest`:
`Notice: /Stage[main]/Sysmon/Package[sysmon]/ensure: ensure changed '13.34.0' to '13.34' (corrective)`

**Comment by geoffrey-rodgers** [comment]
I am working to recreate this issue in an attempt to resolve it. I haven't been successful recreating it yet, but I will continue to try.

**Comment by geoffrey-rodgers** [comment]
@olifre @trenta @Hvid could you detail the steps to recreate this issue, if you are still experiencing it? I cannot do so using PE LTS 2021.7.7 (Puppet Agent 7.28.0).

I've used Puppet to install Chocolatey 1.4.0 and putty 0.78. I then upgraded Chocolatey to 2.2.2. Running the Puppet Agent does not result in the listed changes, unfortunately.

**Comment by trenta** [comment]
I'm running latest puppet 8 and no longer seeing this issue.

**Comment by geoffrey-rodgers** [comment]
Thank you very much for your updates and testing, @trenta and @olifre. I will close this issue for now, and please feel free to re-open it if required.

**Comment by geoffrey-rodgers** [comment]
Thank you very much for your updates and testing, @trenta and @olifre. I will close this issue for now, and please feel free to re-open it if required.
